feat: Add env to control which configuration file to use
mergeability/mergeable pull request #436
Opened 2020-12-11 14:48 UTC by diegomarangoni

Fixes: #429

**Problem:**
Currently there is no way to control which mergeable configuration file will be used, if the one from the PR branch or the one from the default branch.

**Solution:**
This PR implements a new environment variable to control that while maintaining the previous behaviour

2020-12-14 15:19 UTC, shine2lay requested changes

2020-12-14 15:19 UTC, shine2lay commented on lib/configuration/configuration.js
> +    if (process.env.USE_CONFIG_FROM_PULL_REQUEST !== undefined && process.env.USE_CONFIG_FROM_PULL_REQUEST === 'false') {
could you please add a test case for this?

2020-12-15 23:45 UTC, shine2lay approved these changes

2020-12-15 23:47 UTC, shine2lay commented
@diegomarangoni could you please resolve the conflict? I am not able to do it.

2020-12-16 08:08 UTC, diegomarangoni commented
@shine2lay conflict resolved

2020-12-16 18:11 UTC, merged