feat: Allow all option on must_include and must_include inside changeset validator
mergeability/mergeable pull request #611
Opened 2022-02-02 20:53 UTC by taylor-cedar

This adds the ability to use the `all` option on `must_include` and `must_exclude` inside the changeset validator. The code was already there, but it wasn't allowed in the schema. This allows it in the schema.

@shine2lay

2022-02-02 23:22 UTC, shine2lay requested changes
If you could add some tests that shows that `all` sub option is working, that'll be amazing.

2022-02-07 18:53 UTC, taylor-cedar commented
@shine2lay Added tests for this case. Please let me know if that is sufficient

2022-02-08 03:11 UTC, shine2lay approved these changes

2022-02-08 03:12 UTC, shine2lay commented
@taylor-cedar can you please add a changelog entry? then i can merge it. thanks

2022-02-08 22:03 UTC, taylor-cedar commented
@shine2lay Updated changelog

2022-02-09 00:04 UTC, taylor-cedar commented on docs/changelog.rst
> +| November 25, 2021: feat: Add more supported events to baseRef validator `#395 <https://github.com/mergeability/mergeable/issues/395#issuecomment-975763927>`_
Fixed these so that the PR links would work correctly

2022-02-11 14:28 UTC, merged