Added user information for commit validator
mergeability/mergeable pull request #682
Opened 2023-01-05 00:09 UTC by fengwei-tian

1. Added the logic parsing the listCommits response: now it will also have author/committer information in the response
2. Added a new option in the messageSettings: messageType(author_email/committer_email) 
3. Added the logic to filter commit author/committer email

2023-01-22 00:59 UTC, jusx commented
@fengwei-tian Looks good, but could you also update the docs with these new options?

2023-01-23 19:25 UTC, fengwei-tian reviewed
Maybe add - Only check the regex against the xxx

2023-01-23 19:36 UTC, eagraf commented
@jusx just added some documentation for the `message_type` option

2023-01-28 18:12 UTC, jusx requested changes

2023-01-28 18:12 UTC, jusx commented on lib/validators/commit.js
> +    let FAIL_MESSAGE = DEFAULT_FAIL_MESSAGE
Since this isn't a const, I suggest changing this to `failMessage` as the variable name.

2023-02-07 15:17 UTC, eagraf commented
Any updates @jusx, thanks!

2023-02-13 17:37 UTC, ankurd1 commented
Hey @jusx were you able to review this? We'd like to get this merged as it's blocking mergable adoption for us. Thanks!

2023-03-02 01:26 UTC, RemyDeWolf commented
Hi @jusx , we have addressed your comments?
Might taking another look? 
I will personally buy coffee if you have time for us :) https://www.buymeacoffee.com/mergeable

2023-03-02 01:32 UTC, shine2lay approved these changes
LGTM

2023-03-02 01:32 UTC, shine2lay commented
I'll merge it once CI is passing

2023-03-02 01:36 UTC, merged

2023-03-02 20:15 UTC, RemyDeWolf commented
@shine2lay Thank you so much for the merge and the quick release.
We are now setting up mergeable at Rippling

2023-03-02 21:46 UTC, eagraf commented
@shine2lay Would it be possible to deploy release 2.17? That will help us get up and running at Rippling. Thanks!

2023-03-02 22:37 UTC, shine2lay commented
@eagraf our deploy pipeline was broken, I just fixed it, new version should be deployed